### ISSUE TITLE
在compose中运行会退出

### ISSUE THREAD

**Issue by phpng** [twose/swoole-coroutine-docker#3]
```
version: "3"
swoole:
    image: twosee/swoole-coroutine
    container_name: xhgui_swoole
    ports:
        - "${UDP_REV_PORT}:9501"
    restart: always
    networks:
        - web-network
    volumes:
        - ${WWW_ROOT_LOCAL}:${WWW_ROOT_CONTAINER}
        - ${DATA_DIR}/cache:${WWW_ROOT_CONTAINER}/cache
    working_dir: ${WWW_ROOT_CONTAINER}
    stdin_open: true
    tty: true
    read_only: false
    privileged: true
    command: php swoole.php
```
执行 `docker-compose up` 后会报 exited with code 0，container处于重启状态： Restarting (0) 23 seconds ago
